# Generated by Django 5.1.7 on 2025-09-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='client',
            name='senha',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='tipo',
            field=models.CharField(choices=[('A', 'Aluno'), ('N', 'Nutricionista'), ('P', 'Personal Trainer')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
